language: python
python: 3.6
dist: trusty
sudo: true
before_install:
    - pyenv versions
    - pyenv install --skip-existing
    - pyenv rehash
    - pyenv global $(cat .python-version)
    - pip install -U pip pipenv wheel
    - pipenv install --dev --deploy
    - pipenv check
cache:
    - pip
    - directories:
        - /opt/python/
        - /home/travis/.local/share/
script:
    - pipenv run ./scripts/run_lint.sh
    - pipenv run py.test
branches:
    only:
        - master
        - v3
