name: Merge pull requests

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up pip
        run: pip install -U pip pipenv wheel
      - name: Set up Pipenv
        run: pipenv install --dev --deploy
      - name: Run linting script
        run: pipenv run ./scripts/run_lint.sh

  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up pip
        run: pip install -U pip pipenv wheel
      - name: Set up Pipenv
        run: pipenv install --dev --deploy
      - name: Run unit-test script
        run: pipenv run ./scripts/run_tests_unit.sh

  build_and_push_Docker_image:
    runs-on: ubuntu-latest

    needs: [linting, unit_tests]

    env:
      TAG: ${{ github.event.pull_request.head.sha }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build onsdigital/eq-schema-validator Docker image
        run: docker build -t onsdigital/eq-schema-validator:$TAG -f Dockerfile .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to onsdigital/eq-schema-validator with $TAG
        run: docker push onsdigital/eq-schema-validator:$TAG
